export interface IcustomerPost {
    cust_id:number,
    Customer_ID: string,
    Customer_Name: string,
    Both_Supplier_Customer: string,
    ledgeraccount_status:boolean,
    country_id: string,
    state_id: string,
    city_id:string,
    Address_1: string,
    Address_2: string,
    Post_Box: string,
    Land_Line: string,
    Zip_Code: string,
    Fax:string,
    Email_Address: string,
    Website: string,
    OCP_FirstName: string,
    OCP_MiddleName: string,
    OCP_LastName:string,
    OCP_Email: string,
    OCP_Designation: string,
    OCP_Phone: string,
    OCP_Fax: string,
    OCP_MobileNo: string, 
   
}
