export interface IChartPost {
    asset_id: string,
    supp_id: string,
    cust_id: string,
    id: 0,
    AccountNumber: string,
    AccountName: string,
    AccountType: string,
    Opening_Bal: string,
    Budget_Amount: string,
    Opening_Balance_Imported: string,
    Ep_id: string,
    emp_id:string,
    b_id: string,
    o_id:string,
    AccountGroupCode:string,
    ParentGroup:string,
    CurrentLedgerBalance:string,
    Project_Id:string,
}
