export interface IOrganiationPost{
  OId: number,
  OrgId: number,
  OrganizationName: string,
  EmpId: number,
  BId: number,
  ReportingDepartmentId: string,
  CostCenter: boolean,
  MdFirstName: string,
  MdMiddleName: string,
  MdLastName: string,
  MdDesignation: string,
  MdEmail: string,
  MdPhone: string,
  MdFax: string,
  MdMobileNo: string,
  MdPreferredContactPerson: string,
}