export interface IProjectPost{
              
    project_id :number,
    ProjectID: string,
    ProjectName: string,
    CostCenter: string,
    //"LocalName": $scope.P_L_name,
    Risk_Description: string,
    o_id:string,
    //"TypeID": $scope.type,
    Address: string,
    //"Location": $scope.Location,
    Project_Manager: string,
    Plan_startdt:string,
    Plan_Enddt:string,
    Actual_startdt:string,
    Actual_Enddt: string,
    Client:string,
    Contact_no: string,
    Contact_Description:string,
    Contact_StartDt: string,
    Contact_EndDt:string,
    Project_RefNo: string,     
}