export interface JVPost {
    emp_id: string,
    b_id:string,
    o_id: string,
    project_id: 0,
    Narrationseg: string,
    date: Date,
    vochernumber: number,
    
}
export interface RVPost {
    receipt_no: number,
            date: Date,
            received_amount:number,
            amount_in_words: string,
            received_from:string,
            invoice_no: string,
            employer_id: string,
            branchid: string,
            org_un_id: string,
            projectid: string,
            currency:string,
            narration: string,
            bank_name: string,
            branch: string,
            date_of_cheque: Date,
            cheque_number: string,
            Amount:string,
            TransactionType:string,
            Type: string,
}
export interface PVPost {
    receipt_no: number,
            date: Date,
            received_amount:number,
            amount_in_words: string,
            received_from:string,
            invoice_no: string,
            employer_id: string,
            branchid: string,
            org_un_id: string,
            projectid: string,
            currency:string,
            narration: string,
            bank_name: string,
            branch: string,
            date_of_cheque: Date,
            cheque_number: string,
            Amount:string,
            TransactionType:string,
            Type: string,
}